### ISSUE TITLE
Property editingChangedBlock not found

### ISSUE THREAD

**Issue by sbeeckman** [amseddi/AMRatingControl#8]
When trying to set the editingChangedBlock-property, I got an error that the property was not found... Is it possible that the latest version is not on CocoaPods? The .spec-file shows there is a version 1.3.0, but on CocoaPods, only 1.2.0 is available...

**Comment by amseddi** [comment]
Thank you for reporting this issue.
The latest version was not available on CocoaPods but this has now been fixed.
